In [9]:
import numpy as np
arr = np.array( [ [1,2,3] , [4,5,6] , [7,8,9] ] )
print(arr)
print()
print("Dimension: ",arr.ndim)
print("Size: " ,arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Dimension:  2
Size:  9
