In [26]:
import numpy as np
n=int(input('number of elements in list:')) 
l1=list(map(int,input('enter elements inside list1 :').split())) 
l2=list(map(int,input('enter elements inside list2 :').split())) 
arr1=np.array(l1)
arr2=np.array(l2)
print(arr1,arr2)
a=np.concatenate((arr1, arr2))
print(a)
print(np.sort(a))

number of elements in array:5
enter elements inside array :1 3 4 2 5
enter elements inside array :9 5 8 0 6
[1 3 4 2 5] [9 5 8 0 6]
[1 3 4 2 5 9 5 8 0 6]
[0 1 2 3 4 5 5 6 8 9]
