In [33]:
import numpy as np
x= np.arange(9).reshape(3,3)
y=x*2
print("Array 1 :\n",x)
print("Array 2 :\n",y)
n1= np.hstack((x,y))
n2= np.vstack((x,y))
print()
print("Horizontal stack: \n",n1)
print()
print("Vertical stack: \n" ,n2);

Array 1 :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Array 2 :
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

Horizontal stack: 
 [[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]

Vertical stack: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
